# Generated by Django 5.1 on 2024-09-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время отправки"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Частота отправки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                        ],
                        max_length=10,
                        verbose_name="Периодичность отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершена"),
                            ("created", "Создана"),
                            ("running", "Запущена"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="mailing_list",
                        to="client.client",
                        verbose_name="Клиенты",
                    ),
                ),
                (
                    "messages",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                        verbose_name="Сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
